import os
import subprocess
from moviepy.video.io.VideoFileClip import VideoFileClip
from faster_whisper import WhisperModel


def extract_and_separate_audio(video_path, output_dir="output"):
    """
    Extracts audio from a movie file and splits it into 'vocals' and 'background music'.
    """
    # Create output directories if they do not exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    print("[1/3] Extracting main audio track from movie...")
    # Open the video file
    video = VideoFileClip(video_path)
    audio_path = os.path.join(output_dir, "original_audio.wav")
    
    # Save the audio track as a high-quality WAV file
    video.audio.write_audiofile(audio_path, fps=44100, nbytes=2, codec='pcm_s16le')
    video.close()
    print(f"Success: Audio saved to {audio_path}")
    
    print("[2/3] Running Demucs AI to isolate voices from background noises...")
    # Call Demucs via a system command to split the audio track into two stems: vocals and no_vocals
    command = f"demucs --two-stems=vocals {audio_path} -o {output_dir}"
    subprocess.run(command, shell=True, check=True)
    
    print("[3/3] Audio separation complete!")
    print(f"Your isolated voices file is located in: {output_dir}/htdemucs/original_audio/vocals.wav")


def transcribe_vocals(vocals_audio_path, output_srt_path="output/english_movie.srt"):
    """
    Listens to the isolated English voices and creates a time-coded subtitle file.
    """
    print("[1/3] Loading Faster-Whisper AI model into memory...")
    # We use the 'base' model for speed and efficiency in Codespaces. 
    # For maximum accuracy later on a GPU server, you can change this to 'large-v3'.
    # We force it to run on CPU because standard Codespaces don't have dedicated GPUs.
    model = WhisperModel("base", device="cpu", compute_type="float32")
    
    print("[2/3] Transcribing audio track and calculating timestamps...")
    # Transcribe the audio file. We specify language='en' since the movie is in English.
    segments, info = model.transcribe(vocals_audio_path, language="en", beam_size=5)
    
    print(f"Detected language: {info.language} with probability {info.language_probability:.2f}")
    
    print("[3/3] Formatting and saving text to SRT subtitle file...")
    # Subtitle files require a specific format index, timestamps, and the text.
    with open(output_srt_path, "w", encoding="utf-8") as srt_file:
        for index, segment in enumerate(segments, start=1):
            # Convert Whisper's seconds-based timestamps into standard SRT format (HH:MM:SS,mmm)
            start_time = format_timestamp(segment.start)
            end_time = format_timestamp(segment.end)
            
            # Write the block to the file
            srt_file.write(f"{index}\n")
            srt_file.write(f"{start_time} --> {end_time}\n")
            srt_file.write(f"{segment.text.strip()}\n\n")
            
    print(f"Success! English subtitle file saved to: {output_srt_path}")

def format_timestamp(seconds):
    """Helper function to turn raw seconds into HH:MM:SS,mmm format."""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    milliseconds = int((seconds - int(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{milliseconds:03d}"

if __name__ == "__main__":
    # Point this to the exact vocals file generated by Demucs in Step 1
    # Demucs saves files under: output/htdemucs/[input_filename]/vocals.wav
    vocals_file = "output/htdemucs/original_audio/vocals.wav"
    
    if os.path.exists(vocals_file):
        transcribe_vocals(vocals_file)
    else:
        print(f"Error: Could not find the isolated vocal file at '{vocals_file}'. Did Step 1 finish completely?")

